package com.personalfinance.tracker.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * JPA entity representing a spending budget for a specific category and time period.
 *
 * <p>A budget sets an upper spending limit ({@code amountLimit}) on a particular
 * {@link Category} over a defined {@link BudgetPeriod} (weekly, monthly, or yearly).
 * The application can compare actual {@link Transaction} totals against this limit
 * to alert the user when they are approaching or exceeding their budget.</p>
 *
 * <p>The {@code startDate} and {@code endDate} define the exact window during which
 * the budget is active, allowing overlapping or custom-length periods.</p>
 */
@Entity
@Table(name = "budgets")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Budget {

    /**
     * Primary key, auto-generated by the database using an identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Maximum amount the user intends to spend in this budget's category
     * during the specified period. Must be a positive value.
     */
    @NotNull(message = "Amount limit is required")
    @DecimalMin(value = "0.01", message = "Amount limit must be greater than zero")
    @Column(name = "amount_limit", nullable = false, precision = 12, scale = 2)
    private BigDecimal amountLimit;

    /**
     * Recurrence cadence of the budget (weekly, monthly, or yearly).
     * Stored as a string in the database for readability.
     */
    @NotNull(message = "Budget period is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private BudgetPeriod period;

    /**
     * First day of the budget window (inclusive).
     */
    @NotNull(message = "Start date is required")
    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    /**
     * Last day of the budget window (inclusive).
     * Must be on or after {@code startDate}.
     */
    @NotNull(message = "End date is required")
    @Column(name = "end_date", nullable = false)
    private LocalDate endDate;

    /**
     * The user who created this budget.
     * Loaded lazily to avoid unnecessary joins.
     */
    @NotNull(message = "User is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The spending category this budget constrains.
     * Loaded lazily to avoid unnecessary joins.
     */
    @NotNull(message = "Category is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    /**
     * Timestamp recording when the budget was created.
     * Set automatically before the first persist operation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * JPA lifecycle callback invoked before the entity is first persisted.
     * Initialises {@code createdAt} to the current time.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }
}
