package com.personalfinance.tracker.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * JPA entity representing a user-defined transaction category.
 *
 * <p>Categories allow users to organise their {@link Transaction transactions}
 * into logical groups such as "Groceries", "Salary", or "Entertainment".
 * Each category is scoped to a specific {@link TransactionType} so that
 * income and expense categories remain distinct.</p>
 *
 * <p>An optional {@code icon} field lets the front-end display a visual
 * indicator next to the category name.</p>
 */
@Entity
@Table(name = "categories")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Category {

    /**
     * Primary key, auto-generated by the database using an identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable name of the category (e.g. "Rent", "Freelance Income").
     * Must be between 1 and 100 characters.
     */
    @NotBlank(message = "Category name is required")
    @Size(min = 1, max = 100, message = "Category name must be between 1 and 100 characters")
    @Column(nullable = false, length = 100)
    private String name;

    /**
     * Indicates whether this category applies to income or expense transactions.
     * Stored as a string in the database for readability.
     */
    @NotNull(message = "Transaction type is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private TransactionType type;

    /**
     * Optional icon identifier (e.g. a Material Icons name or emoji)
     * used by the front-end to visually represent this category.
     */
    @Column(length = 50)
    private String icon;

    /**
     * The user who owns this category.
     * Loaded lazily to avoid unnecessary joins when only category data is needed.
     */
    @NotNull(message = "User is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Timestamp recording when the category was created.
     * Set automatically before the first persist operation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * JPA lifecycle callback invoked before the entity is first persisted.
     * Initialises {@code createdAt} to the current time.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }
}
