package com.personalfinance.tracker.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * JPA entity representing a user's financial savings or investment goal.
 *
 * <p>A financial goal tracks progress toward a monetary target (e.g. "Emergency Fund",
 * "Vacation Savings"). The {@code currentAmount} is updated as the user logs
 * contributions, and the {@code status} transitions from {@link GoalStatus#ACTIVE}
 * to {@link GoalStatus#COMPLETED} once the target is reached, or to
 * {@link GoalStatus#CANCELLED} if the user abandons the goal.</p>
 *
 * <p>The {@code deadline} gives a target completion date so the application can
 * display progress indicators and send reminders.</p>
 */
@Entity
@Table(name = "financial_goals")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FinancialGoal {

    /**
     * Primary key, auto-generated by the database using an identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Descriptive name for the goal (e.g. "New Car Down Payment").
     * Must be between 1 and 200 characters.
     */
    @NotBlank(message = "Goal name is required")
    @Size(min = 1, max = 200, message = "Goal name must be between 1 and 200 characters")
    @Column(nullable = false, length = 200)
    private String name;

    /**
     * Total monetary amount the user aims to accumulate.
     * Must be a positive value.
     */
    @NotNull(message = "Target amount is required")
    @DecimalMin(value = "0.01", message = "Target amount must be greater than zero")
    @Column(name = "target_amount", nullable = false, precision = 12, scale = 2)
    private BigDecimal targetAmount;

    /**
     * Amount accumulated toward the goal so far.
     * Defaults to zero when the goal is first created.
     */
    @NotNull(message = "Current amount is required")
    @Column(name = "current_amount", nullable = false, precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal currentAmount = BigDecimal.ZERO;

    /**
     * Target date by which the user hopes to reach the goal.
     */
    @NotNull(message = "Deadline is required")
    @Column(nullable = false)
    private LocalDate deadline;

    /**
     * Current lifecycle status of the goal (active, completed, or cancelled).
     * Stored as a string in the database for readability.
     */
    @NotNull(message = "Goal status is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private GoalStatus status = GoalStatus.ACTIVE;

    /**
     * The user who owns this financial goal.
     * Loaded lazily to avoid unnecessary joins.
     */
    @NotNull(message = "User is required")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Timestamp recording when the goal was created.
     * Set automatically before the first persist operation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp recording when the goal record was last modified.
     * Updated automatically before every update operation.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * JPA lifecycle callback invoked before the entity is first persisted.
     * Initialises both {@code createdAt} and {@code updatedAt} to the current time.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /**
     * JPA lifecycle callback invoked before each subsequent update.
     * Refreshes {@code updatedAt} to the current time.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
