package com.personalfinance.tracker.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * JPA entity representing an application user.
 *
 * <p>Each user owns a personal set of {@link Category categories},
 * {@link Transaction transactions}, {@link Budget budgets}, and
 * {@link FinancialGoal financial goals}. Authentication is handled
 * via a BCrypt-hashed password stored alongside a unique username
 * and email address.</p>
 *
 * <p>Timestamps are managed automatically through JPA lifecycle
 * callbacks ({@link #onCreate()} and {@link #onUpdate()}).</p>
 */
@Entity
@Table(name = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /**
     * Primary key, auto-generated by the database using an identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique login name chosen by the user.
     * Must be between 3 and 50 characters long.
     */
    @NotBlank(message = "Username is required")
    @Size(min = 3, max = 50, message = "Username must be between 3 and 50 characters")
    @Column(nullable = false, unique = true, length = 50)
    private String username;

    /**
     * Unique email address used for account verification and notifications.
     * Validated against standard email format constraints.
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Email must be a valid email address")
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * BCrypt-hashed password. The raw password is never stored.
     */
    @NotBlank(message = "Password is required")
    @Column(nullable = false)
    private String password;

    /**
     * Timestamp recording when the user account was created.
     * Set automatically before the first persist operation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp recording when the user record was last modified.
     * Updated automatically before every update operation.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * JPA lifecycle callback invoked before the entity is first persisted.
     * Initialises both {@code createdAt} and {@code updatedAt} to the current time.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /**
     * JPA lifecycle callback invoked before each subsequent update.
     * Refreshes {@code updatedAt} to the current time.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
